global(workDirectory="/var/spool/rsyslog")

module(load="imudp")
module(load="imtcp")
module(load="imfile" PollingInterval="5")

template(
  name="ArtemisForwardFormat"
  type="string"
  string="<%pri%>1 %timegenerated:::date-rfc3339% %hostname% %programname% - - - %msg%\n"
)

ruleset(name="forward_logs") {
  action(
    type="omfwd"
    target="artgra01p"
    port="1514"
    protocol="tcp"
    template="ArtemisForwardFormat"
    action.resumeRetryCount="-1"
    queue.type="LinkedList"
    queue.filename="graylog"
  )

  action(
    type="omfwd"
    target="artspl01p"
    port="1515"
    protocol="tcp"
    template="ArtemisForwardFormat"
    action.resumeRetryCount="-1"
    queue.type="LinkedList"
    queue.filename="splunk"
  )
}

input(type="imudp" port="514" ruleset="forward_logs")
input(type="imtcp" port="514" ruleset="forward_logs")

input(
  type="imfile"
  File="/var/lib/docker/containers/*/*-json.log"
  Tag="docker-json:"
  Facility="local7"
  Severity="info"
  PersistStateInterval="100"
  addMetadata="on"
  ruleset="forward_logs"
)
