[tcp://1515]
disabled = 0
index = artemis
sourcetype = artemis:syslog
connection_host = dns

[http]
disabled = 0
enableSSL = 0
port = 8088

[http://artemis_hec]
disabled = 0
token = 00000000-0000-0000-0000-000000000000
index = artemis
indexes = artemis
sourcetype = _json
